name: Makefile CI

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main", "dev"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Tests
      run: make test
